FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /app

# Copy Python project files
COPY python/ ./

# Install dependencies
RUN uv sync --locked

EXPOSE 8000

# Run the application.
CMD ["uv", "run", "python", "main.py", "--host", "0.0.0.0", "--port", "8000"]
